from .artpl import NosferatuMainSource
from .aosabook import AosaBookSource
from .blogspot import BlogSpotSource
from .flask import FlaskSource
from .harp import HarpMainSource
from .haskell import HaskellSource
from .histmag import HistmagSource
from .medium import MediumSource
from .readthedocs import ReadTheDocsBookSource
from .rust import RustBookSource
from .tumblr import TumblrArchiveSource
from .wikipedia import WikipediaSource
