from .artpl import NosferatuMainSource
from .aosabook import AosaBookSource
from .blogspot import BlogSpotSource
from .dzieje import DziejePlSource
from .flask import FlaskSource
from .google_sre import GoogleSRESource
from .harp import HarpMainSource
from .haskell import HaskellSource
from .histmag import HistmagSource
from .medium import MediumSource
from. oreilly import OReillySource
from .readthedocs import ReadTheDocsBookSource
from .rust import RustBookSource
from .tumblr import TumblrArchiveSource
from .wikipedia import WikipediaSource
